/*
-- Query: SELECT * FROM apps.mm_parms
-- Date: 2017-12-10 11:15
*/
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','0','Smiley Bill',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','1','Curtis',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','10','Colligan II',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','11','T. Hampton',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','12','Corrigan',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','13','Osmond',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','14','Annette',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','15','Cheryl',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','16','Brad B.',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','17','Duff',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','18','Rico',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','19','Holmsy',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','2','Delecki II',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','20','Kaplan',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','21','J. Hampton',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','22','Ruffer',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','23','King',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','24','GNIK',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','25','DAK / TIFF',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','26','Farts',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','27','G. Henson',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','28','Hoy',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','29','T. Hicks',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','3','BNB',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','30','AJR',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','31','DT',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','32','Roger',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','33','Stickman',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','34','Gingus',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','35','Farts',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','36','Jameson',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','37','Johnny Boy',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','38','L. Lee',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','39','Frank',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','4','Robby',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','40','D. Lutz',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','41','Brant',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','42','John Lee',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','43','Dunny',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','44','CZECH',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','45','RT / JR',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','46','Buda / JG',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','47','T. Harris',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','48','Jeff',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','49','Z',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','5','York',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','50','Katherine',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','51','Denny',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','52','Leo',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','53','Friedman',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','54','Haegle',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','55','Hufton',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','56','Lynn',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','57','Shoemaker',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','58','Korab',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','59','Drew',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','6','Cindy M.',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','60','Ciglo',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','61','T. Lutz',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','62','Hon Sheriff',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','63','Go Green',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','64','Chris P.',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','65','D Scott',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','66','Farts',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','67','York II',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','68','Batch',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','69','Colleen',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','7','Willie',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','70','Leo',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','71','Billy',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','72','Jimmy',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','73','Jimmer / Buda',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','74','Jimmer',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','75','Dirty B',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','76','Jeremy',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','77','Matt M.',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','78','Tatti',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','79','Andy G.',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','8','Farts',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','80','Vac',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','81','JG',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','82','Buda',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','83','R. Henson',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','84','J. Furyk',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','85','Friedman',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','86','Wiemer',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','87','Forbush',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','88','Jimmer / Roger',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','89','Colligan',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','9','T. Furyk',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','90','Pat H',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','91','Delecki',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','92','R. Henson',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','93','Craig J.',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','94','Rolli',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','95','CISLO',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','96','M. Hicks',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','97','Polly',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','98','C. Baker',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player','99','Rod',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Player_Numbers','1','0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Team_Numbers','Losing','9,8,0,2,1,7,3,6,4,5',' ');
INSERT INTO `mm_parms` (`Parm_Type`,`Parm_Id`,`Parm_Value`,`Parm_Value2`) VALUES ('Team_Numbers','Winning','8,9,0,5,7,4,2,1,3,6',' ');
